#Faça um programa que leia um valor e mostre na tela a sua tabuada
num=int(input('Insira um  menro : '))
print('A tabiada do numero {} é : '.format(num))
print('-'*12)
print('{} x {:2} = {}'.format(num,1,num*1))
print('{} x {:2} = {}'.format(num,2,num*2))
print('{} x {:2} = {}'.format(num,3,num*3))
print('{} x {:2} = {}'.format(num,4,num*4))
print('{} x {:2} = {}'.format(num,5,num*5))
print('{} x {:2} = {}'.format(num,6,num*6))
print('{} x {:2} = {}'.format(num,7,num*7))
print('{} x {:2} = {}'.format(num,8,num*8))
print('{} x {:2} = {}'.format(num,9,num*9))
print('{} x {} = {}'.format(num,10,num*10))
print('{} x {} = {}'.format(num,11,num*11))
print('{} x {} = {}'.format(num,12,num*12))
print('-'*12)
